name: PM2 Manager Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v3
        
      # Trigger API reload to restart PM2 process
      - name: Trigger API reload IN VPS2
        run: |
          curl -X POST https://1pm2.noerror.studio/api/restart/5 \
          -H "Content-Type: application/json"

      - name: Trigger API reload IN VPS5
        run: |
          curl -X POST https://2pm2.noerror.studio/api/restart/4 \
          -H "Content-Type: application/json"
