name: PM2 Manager Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - uses: actions/checkout@v3
        
      # Trigger API reload to restart PM2 process
      - name: Trigger API reload
        run: |
          curl -X POST https://pm2-manager.noerror.studio/api/restart/0 \
          -H "Content-Type: application/json"
